// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1M0p5T5bpTzKh8AYDKmL-V7O2Ul-Qcsg',
    appId: '1:761060143276:web:817c7882e412cc9120af09',
    messagingSenderId: '761060143276',
    projectId: 'fire-dany',
    authDomain: 'fire-dany.firebaseapp.com',
    storageBucket: 'fire-dany.appspot.com',
    measurementId: 'G-R8YTQ5PYCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFmEcaJA1BNIZlhxyfPeLDC5FEgHU4nQ8',
    appId: '1:761060143276:android:a3e6c78ebdee09c320af09',
    messagingSenderId: '761060143276',
    projectId: 'fire-dany',
    storageBucket: 'fire-dany.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1M0p5T5bpTzKh8AYDKmL-V7O2Ul-Qcsg',
    appId: '1:761060143276:web:cd361e9c2a94583c20af09',
    messagingSenderId: '761060143276',
    projectId: 'fire-dany',
    authDomain: 'fire-dany.firebaseapp.com',
    storageBucket: 'fire-dany.appspot.com',
    measurementId: 'G-QQ89BD5DZM',
  );
}
